{{- if not .Values.eula.accepted }}
{{- fail "EULA must be accepted. Please set 'eula.accepted=true' in your values.yaml or via --set. See https://inductiveautomation.com/ignition/license" }}
{{- end }}
{{- $httpPort := "" }}
{{- $httpsPort := "" }}
{{- $ganPort := "" }}
{{- range .Values.service.ports }}
  {{- if eq .name "http" }}
    {{- $httpPort = .port }}
  {{- else if eq .name "https" }}
    {{- $httpsPort = .port }}
  {{- else if eq .name "gan" }}
    {{- $ganPort = .port }}
  {{- end }}
{{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ignition.fullname" . }}
  labels:
    {{- include "ignition.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ignition.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "ignition.fullname" . }}
  replicas: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ignition.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $httpPort }}
              protocol: TCP
            - name: https
              containerPort: {{ $httpsPort }}
              protocol: TCP
            - name: gan
              containerPort: {{ $ganPort }}
              protocol: TCP
          env:
            - name: GATEWAY_HTTP_PORT
              value: "{{ $httpPort }}"
            - name: GATEWAY_HTTPS_PORT
              value: "{{ $httpsPort }}"
            - name: GATEWAY_GAN_PORT
              value: "{{ $ganPort }}"
          {{- if .Values.eula.accepted }}
            - name: ACCEPT_IGNITION_EULA
              value: "Y"
          {{- end}}
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          livenessProbe:
            httpGet:
              path: /StatusPing
              port: http
          readinessProbe: # Check for RUNNING status
            exec:
              command:
                - sh
                - -c
                - 'curl -sf http://localhost:{{ $httpPort }}/StatusPing | grep -q RUNNING'
            initialDelaySeconds: 10
            periodSeconds: 5
      {{- if .Values.volumeClaimTemplates }}
          volumeMounts:
            - name: {{ (index .Values.volumeClaimTemplates 0).metadata.name }}
              mountPath: /usr/local/bin/ignition/data
      initContainers:
        - name: "init-{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: # Mount PVC to a temp dir; if non-empty, copy data from the image to the temp dir
            - |
              if [ ! -f /tmp/gw-data/gateway.xml_clean ]; 
              then
                cp -a /usr/local/bin/ignition/data/* /tmp/gw-data
                echo "Volume initialized"
              else
                echo "Volume already initialized, passing"
              fi
          volumeMounts:
            - name: {{ (index .Values.volumeClaimTemplates 0).metadata.name }}
              mountPath: /tmp/gw-data
      {{- end }}
    {{- with .Values.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 4 }}
    {{- end }}